-- 1. USERS TABLE
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  county VARCHAR(100),
  role ENUM('user', 'staff', 'admin') DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. FEEDBACK TABLE
CREATE TABLE feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100),
  county VARCHAR(100),
  feedback_category VARCHAR(50),
  feedback_subcategory VARCHAR(50),
  details VARCHAR(50) DEFAULT NULL,
  description TEXT,
  photo VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. DEPARTMENTS TABLE
CREATE TABLE departments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT
);

-- 4. STAFF TABLE
CREATE TABLE staff (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  department INT,
  role VARCHAR(50),
  FOREIGN KEY (department) REFERENCES departments(id)
);

-- 5. COMMENTS TABLE
CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  feedback INT NOT NULL,
  user INT NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (feedback) REFERENCES feedback(id),
  FOREIGN KEY (user) REFERENCES users(id)
);

-- 6. REACTIONS TABLE
CREATE TABLE reactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user INT NOT NULL,
  feedback INT NOT NULL,
  type ENUM('like', 'dislike', 'star') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user, feedback, type),
  FOREIGN KEY (user) REFERENCES users(id),
  FOREIGN KEY (feedback) REFERENCES feedback(id)
);

-- 7. NOTIFICATIONS TABLE
CREATE TABLE notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user INT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user) REFERENCES users(id)
);

-- 8. LOGS TABLE
CREATE TABLE logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  actor VARCHAR(100) NOT NULL,
  action TEXT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
